//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 10:14:56 AM COT 
//


package https.recursoshumanos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the https.recursoshumanos package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RecursosHumanosEjbException_QNAME = new QName("https://recursoshumanos.erpsaas", "RecursosHumanosEjbException");
    private final static QName _ConsultarCompetenciasLaborales_QNAME = new QName("https://recursoshumanos.erpsaas", "consultarCompetenciasLaborales");
    private final static QName _ConsultarCompetenciasLaboralesResponse_QNAME = new QName("https://recursoshumanos.erpsaas", "consultarCompetenciasLaboralesResponse");
    private final static QName _IngresarHojaDeVidaAspirante_QNAME = new QName("https://recursoshumanos.erpsaas", "ingresarHojaDeVidaAspirante");
    private final static QName _IngresarHojaDeVidaAspiranteResponse_QNAME = new QName("https://recursoshumanos.erpsaas", "ingresarHojaDeVidaAspiranteResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: https.recursoshumanos
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RecursosHumanosEjbException }
     * 
     */
    public RecursosHumanosEjbException createRecursosHumanosEjbException() {
        return new RecursosHumanosEjbException();
    }

    /**
     * Create an instance of {@link ConsultarCompetenciasLaborales }
     * 
     */
    public ConsultarCompetenciasLaborales createConsultarCompetenciasLaborales() {
        return new ConsultarCompetenciasLaborales();
    }

    /**
     * Create an instance of {@link ConsultarCompetenciasLaboralesResponse }
     * 
     */
    public ConsultarCompetenciasLaboralesResponse createConsultarCompetenciasLaboralesResponse() {
        return new ConsultarCompetenciasLaboralesResponse();
    }

    /**
     * Create an instance of {@link IngresarHojaDeVidaAspirante }
     * 
     */
    public IngresarHojaDeVidaAspirante createIngresarHojaDeVidaAspirante() {
        return new IngresarHojaDeVidaAspirante();
    }

    /**
     * Create an instance of {@link IngresarHojaDeVidaAspiranteResponse }
     * 
     */
    public IngresarHojaDeVidaAspiranteResponse createIngresarHojaDeVidaAspiranteResponse() {
        return new IngresarHojaDeVidaAspiranteResponse();
    }

    /**
     * Create an instance of {@link IngresoHojaVidaDTO }
     * 
     */
    public IngresoHojaVidaDTO createIngresoHojaVidaDTO() {
        return new IngresoHojaVidaDTO();
    }

    /**
     * Create an instance of {@link CompetenciaWebDTO }
     * 
     */
    public CompetenciaWebDTO createCompetenciaWebDTO() {
        return new CompetenciaWebDTO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecursosHumanosEjbException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://recursoshumanos.erpsaas", name = "RecursosHumanosEjbException")
    public JAXBElement<RecursosHumanosEjbException> createRecursosHumanosEjbException(RecursosHumanosEjbException value) {
        return new JAXBElement<RecursosHumanosEjbException>(_RecursosHumanosEjbException_QNAME, RecursosHumanosEjbException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCompetenciasLaborales }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://recursoshumanos.erpsaas", name = "consultarCompetenciasLaborales")
    public JAXBElement<ConsultarCompetenciasLaborales> createConsultarCompetenciasLaborales(ConsultarCompetenciasLaborales value) {
        return new JAXBElement<ConsultarCompetenciasLaborales>(_ConsultarCompetenciasLaborales_QNAME, ConsultarCompetenciasLaborales.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarCompetenciasLaboralesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://recursoshumanos.erpsaas", name = "consultarCompetenciasLaboralesResponse")
    public JAXBElement<ConsultarCompetenciasLaboralesResponse> createConsultarCompetenciasLaboralesResponse(ConsultarCompetenciasLaboralesResponse value) {
        return new JAXBElement<ConsultarCompetenciasLaboralesResponse>(_ConsultarCompetenciasLaboralesResponse_QNAME, ConsultarCompetenciasLaboralesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngresarHojaDeVidaAspirante }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://recursoshumanos.erpsaas", name = "ingresarHojaDeVidaAspirante")
    public JAXBElement<IngresarHojaDeVidaAspirante> createIngresarHojaDeVidaAspirante(IngresarHojaDeVidaAspirante value) {
        return new JAXBElement<IngresarHojaDeVidaAspirante>(_IngresarHojaDeVidaAspirante_QNAME, IngresarHojaDeVidaAspirante.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IngresarHojaDeVidaAspiranteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "https://recursoshumanos.erpsaas", name = "ingresarHojaDeVidaAspiranteResponse")
    public JAXBElement<IngresarHojaDeVidaAspiranteResponse> createIngresarHojaDeVidaAspiranteResponse(IngresarHojaDeVidaAspiranteResponse value) {
        return new JAXBElement<IngresarHojaDeVidaAspiranteResponse>(_IngresarHojaDeVidaAspiranteResponse_QNAME, IngresarHojaDeVidaAspiranteResponse.class, null, value);
    }

}
